Mimic.copy(Mojito)
Mimic.copy(HTTPoison)
Mimic.copy(Stripe.Connect.OAuth)
Mimic.copy(Stripe.Customer)
Mimic.copy(Stripe.Plan)
Mimic.copy(Stripe.Token)
Mimic.copy(Stripe.Subscription)
Mimic.copy(Stripe.SubscriptionItem)
Mimic.copy(Stripe.Invoice)
Mimic.copy(Stripe.Card)
Mimic.copy(Cloudflare.DnsRecord)
Mimic.copy(Core.Conduit.Broker)
Mimic.copy(Core.Services.Shell.Pods)
Mimic.copy(Core.Shell.Scm)
Mimic.copy(Kazan)
Mimic.copy(WorkOS.SSO)

Mimic.copy(Goth.Token)
Mimic.copy(GoogleApi.CloudResourceManager.V3.Api.Projects)
Mimic.copy(GoogleApi.CloudResourceManager.V3.Api.Operations)
Mimic.copy(GoogleApi.IAM.V1.Api.Projects)

Mimic.copy(Core.Clients.Vault)

ExUnit.start()
