defmodule Core.PubSub.VersionCreated, do: use Piazza.PubSub.Event
defmodule Core.PubSub.VersionUpdated, do: use Piazza.PubSub.Event
defmodule Core.PubSub.DockerNotification, do: use Piazza.PubSub.Event
defmodule Core.PubSub.InstallationUpdated, do: use Piazza.PubSub.Event
defmodule Core.PubSub.SubscriptionUpdated, do: use Piazza.PubSub.Event
defmodule Core.PubSub.SubscriptionCreated, do: use Piazza.PubSub.Event
defmodule Core.PubSub.IncidentCreated, do: use Piazza.PubSub.Event
defmodule Core.PubSub.IncidentUpdated, do: use Piazza.PubSub.Event
defmodule Core.PubSub.IncidentMessageCreated, do: use Piazza.PubSub.Event
defmodule Core.PubSub.IncidentMessageUpdated, do: use Piazza.PubSub.Event
defmodule Core.PubSub.IncidentMessageDeleted, do: use Piazza.PubSub.Event
defmodule Core.PubSub.NotificationCreated, do: use Piazza.PubSub.Event
