apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: plural-uptime-rules
spec:
  groups:
  - name: plural
    rules:
    - alert: PluralDBUp
      expr: sum(up{namespace="plural", pod=~"plural-plural-[0-9]*"}) < 1
      for: 5m
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: No plural db replicas are up
        description: Validate there are not any issues in the cluster or database configuration
    - alert: PluralHydraDBUp
      expr: sum(up{namespace="plural", pod=~"plural-hydra-[0-9]*"}) < 1
      for: 5m
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: No plural hydra db replicas are up
        description: Validate there are not any issues in the cluster or database configuration
    - alert: PluralAPIUp
      expr: sum(up{namespace="plural", pod=~"plural-api-.*-.*"}) < 1
      for: 5m
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: No plural api replicas are up
        description: validate no code changes are infrastructure issues are causing unavailability
    - alert: PluralRtcUp
      expr: sum(up{namespace="plural", pod=~"plural-rtc-.*-.*"}) < 1
      for: 5m
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: No plural rtc replicas are up
        description: validate no code changes are infrastructure issues are causing unavailability
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: example
    role: alert-rules
  name: plural-rules
spec:
  groups:
  - name: plural
    rules:
    - alert: PluralHydraCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"plural-hydra-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"plural-hydra-[0-9]+", resource="cpu"})
        )  > 0.6
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: plural hydra dbs's cpu has gotten too high
        description: the cpu utilization of your plural hydra is higher than recommended
    - alert: PluralHydraMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"plural-hydra-[0-9]+",image!="",container!=""})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"plural-hydra-[0-9]+"})
        )  > 1
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: plural hydra db's memory has gotten too high
        description: the memory utilization of your plural hydra db is higher than recommended
    - alert: PluralDbCPU
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"plural-plural-[0-9]+"}[5m])) 
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"plural-plural-[0-9]+", resource="cpu"})
        )  > 0.6
      for: 5m
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: plural's postgres cpu has gotten too high
        description: the cpu utilization of your plural deployment's postgres db is higher than recommended
    - alert: PluralDbMEM
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"plural-plural-[0-9]+",image!="",container!=""})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"plural-plural-[0-9]+"})
        )  > 1
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: plural postgres memory has gotten too high
        description: the memory utilization of your plural deployment's postgres db is higher than recommended
    - alert: PluralShellHangs
      expr: sum(kube_pod_status_phase{phase="Pending",namespace="plrl-shell"}) > 0
      for: 5m
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: count of hanging shell pods
        description: if shells aren't starting there's probably something critical failing, ie a misconfigured docker image
