export enum Condition {
  BeEnabled = 'be.enabled',
  BeDisabled = 'be.disabled',
  BeChecked = 'be.checked',
  BeVisible = 'be.visible',
  Contain = 'contain',
  Exist = 'exist',
  HaveClass = 'have.class',
  HaveLength = 'have.length',
  HaveValue = 'have.value',
  Include = 'include',
  NotBe = 'not.be',
  NotBeChecked = 'not.be.checked',
  NotBeVisible = 'not.be.visible',
  NotBeEmpty = 'not.be.empty',
  NotContain = 'not.contain',
  NotExist = 'not.exist',
  NotHaveClass = 'not.have.class',
}
