/* eslint-disable */

import { clientsClaim } from 'workbox-core'
import { ExpirationPlugin } from 'workbox-expiration'
import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { StaleWhileRevalidate } from 'workbox-strategies'

clientsClaim()

// Precache all the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// Filter out the "index.html" so that it is not cached as it breaks
// the application when the code changes and SW caches it
// @ts-expect-error
const precache = self.__WB_MANIFEST.filter(
  (file) => !file.url.includes('index.html')
)
precacheAndRoute(precache)

const isSameOrigin = (url) => url.origin === self.location.origin
const shouldCache = (pathname) =>
  Boolean(
    pathname.endsWith('.png') ||
      pathname.endsWith('.svg') ||
      pathname.endsWith('.jpg') ||
      pathname.endsWith('.woff2')
  )

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
// Add in any other file extensions or routing criteria as needed.
registerRoute(
  ({ url }) => isSameOrigin(url) && shouldCache(url.pathname),
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used cache items are removed.
      new ExpirationPlugin({ maxEntries: 500 }),
    ],
  })
)
